
# Complete mapping to 6 main regions
country_to_main_region = {
    # Asia
    'Asia': 'Asia',
    'Southern Asia': 'Asia',
    'Eastern Asia': 'Asia',
    'South-eastern Asia': 'Asia',
    'Western Asia': 'Asia',
    'Central Asia': 'Asia',
    'China': 'Asia',
    'China, mainland': 'Asia',
    'China, Taiwan Province of': 'Asia',
    'China, Hong Kong SAR': 'Asia',
    'China, Macao SAR': 'Asia',
    'India': 'Asia',
    'Indonesia': 'Asia',
    'Pakistan': 'Asia',
    'Thailand': 'Asia',
    'Philippines': 'Asia',
    'Malaysia': 'Asia',
    'Viet Nam': 'Asia',
    'Bangladesh': 'Asia',
    'Japan': 'Asia',
    'Iran (Islamic Republic of)': 'Asia',
    'Myanmar': 'Asia',
    'Republic of Korea': 'Asia',
    "Democratic People's Republic of Korea": 'Asia',
    'Afghanistan': 'Asia',
    'Sri Lanka': 'Asia',
    'Iraq': 'Asia',
    "Lao People's Democratic Republic": 'Asia',
    'Saudi Arabia': 'Asia',
    'Nepal': 'Asia',
    'Cambodia': 'Asia',
    'Syrian Arab Republic': 'Asia',
    'Yemen': 'Asia',
    'Mongolia': 'Asia',
    'Lebanon': 'Asia',
    'Jordan': 'Asia',
    'United Arab Emirates': 'Asia',
    'Kuwait': 'Asia',
    'Palestine': 'Asia',
    'Oman': 'Asia',
    'Singapore': 'Asia',
    'Bhutan': 'Asia',
    'Timor-Leste': 'Asia',
    'Qatar': 'Asia',
    'Bahrain': 'Asia',
    'Brunei Darussalam': 'Asia',
    'Maldives': 'Asia',
    'Cyprus': 'Asia',  # Geographically in Asia, sometimes considered European
    'Armenia': 'Asia',
    'Azerbaijan': 'Asia',
    'Georgia': 'Asia',
    'Kazakhstan': 'Asia',
    'Kyrgyzstan': 'Asia',
    'Tajikistan': 'Asia',
    'Turkmenistan': 'Asia',
    'Uzbekistan': 'Asia',
    'Russia (Asian part)': 'Asia',  # Transcontinental, but including for completeness

    # North America
    'Americas': 'North America',
    'Northern America': 'North America',
    'Central America': 'North America',
    'Caribbean': 'North America',
    'North America': 'North America',
    'United States of America': 'North America',
    'Mexico': 'North America',
    'Canada': 'North America',
    'Cuba': 'North America',
    'Guatemala': 'North America',
    'Dominican Republic': 'North America',
    'El Salvador': 'North America',
    'Honduras': 'North America',
    'Nicaragua': 'North America',
    'Costa Rica': 'North America',
    'Jamaica': 'North America',
    'Haiti': 'North America',
    'Panama': 'North America',
    'Puerto Rico': 'North America',
    'Trinidad and Tobago': 'North America',
    'Belize': 'North America',
    'Guadeloupe': 'North America',
    'Barbados': 'North America',
    'Bahamas': 'North America',
    'Antigua and Barbuda': 'North America',
    'Grenada': 'North America',
    'Saint Vincent and the Grenadines': 'North America',
    'Dominica': 'North America',
    'Saint Lucia': 'North America',
    'Saint Kitts and Nevis': 'North America',
    'Martinique': 'North America',
    'Greenland': 'North America',
    'Bermuda': 'North America',

    # South America
    'South America': 'South America',
    'Brazil': 'South America',
    'Argentina': 'South America',
    'Colombia': 'South America',
    'Peru': 'South America',
    'Ecuador': 'South America',
    'Venezuela (Bolivarian Republic of)': 'South America',
    'Bolivia (Plurinational State of)': 'South America',
    'Paraguay': 'South America',
    'Chile': 'South America',
    'Guyana': 'South America',
    'Uruguay': 'South America',
    'Suriname': 'South America',
    'French Guiana': 'South America',

    # Europe
    'Europe': 'Europe',
    'European Union (27)': 'Europe',
    'Eastern Europe': 'Europe',
    'Western Europe': 'Europe',
    'Southern Europe': 'Europe',
    'Northern Europe': 'Europe',
    'France': 'Europe',
    'Germany': 'Europe',
    'Poland': 'Europe',
    'TÃ¼rkiye': 'Europe',  # Transcontinental, often considered European
    'Turkey': 'Europe',
    'Italy': 'Europe',
    'Spain': 'Europe',
    'Ukraine': 'Europe',
    'Netherlands (Kingdom of the)': 'Europe',
    'Romania': 'Europe',
    'Hungary': 'Europe',
    'Denmark': 'Europe',
    'Czechoslovakia': 'Europe',
    'Austria': 'Europe',
    'Yugoslav SFR': 'Europe',
    'Greece': 'Europe',
    'Belgium-Luxembourg': 'Europe',
    'Sweden': 'Europe',
    'Ireland': 'Europe',
    'Bulgaria': 'Europe',
    'Belarus': 'Europe',
    'Czechia': 'Europe',
    'Belgium': 'Europe',
    'Switzerland': 'Europe',
    'Finland': 'Europe',
    'Portugal': 'Europe',
    'Serbia': 'Europe',
    'Lithuania': 'Europe',
    'Slovakia': 'Europe',
    'Norway': 'Europe',
    'Croatia': 'Europe',
    'Republic of Moldova': 'Europe',
    'Albania': 'Europe',
    'Latvia': 'Europe',
    'Estonia': 'Europe',
    'Slovenia': 'Europe',
    'Bosnia and Herzegovina': 'Europe',
    'North Macedonia': 'Europe',
    'Iceland': 'Europe',
    'Luxembourg': 'Europe',
    'Montenegro': 'Europe',
    'Malta': 'Europe',
    'Monaco': 'Europe',
    'Andorra': 'Europe',
    'Liechtenstein': 'Europe',
    'San Marino': 'Europe',
    'Holy See': 'Europe',
    'Russian Federation': 'Europe',  # Transcontinental, but European part
    'USSR': 'Europe',
    'Serbia and Montenegro': 'Europe',

    # Africa
    'Africa': 'Africa',
    'Eastern Africa': 'Africa',
    'Northern Africa': 'Africa',
    'Western Africa': 'Africa',
    'Southern Africa': 'Africa',
    'Middle Africa': 'Africa',
    'South Africa': 'Africa',
    'Egypt': 'Africa',
    'Nigeria': 'Africa',
    'Kenya': 'Africa',
    'Morocco': 'Africa',
    'Sudan (former)': 'Africa',
    'Mauritius': 'Africa',
    'United Republic of Tanzania': 'Africa',
    'Zimbabwe': 'Africa',
    'Uganda': 'Africa',
    'Democratic Republic of the Congo': 'Africa',
    'Ethiopia': 'Africa',
    'Madagascar': 'Africa',
    "CÃ´te d'Ivoire": 'Africa',
    "Côte d'Ivoire": 'Africa',
    'Eswatini': 'Africa',
    'Cameroon': 'Africa',
    'Malawi': 'Africa',
    'Zambia': 'Africa',
    'Mozambique': 'Africa',
    'Ghana': 'Africa',
    'Algeria': 'Africa',
    'Sudan': 'Africa',
    'Ethiopia PDR': 'Africa',
    'Mali': 'Africa',
    'Angola': 'Africa',
    'RÃ©union': 'Africa',
    'Senegal': 'Africa',
    'Guinea': 'Africa',
    'Burkina Faso': 'Africa',
    'Tunisia': 'Africa',
    'Niger': 'Africa',
    'Chad': 'Africa',
    'Somalia': 'Africa',
    'Benin': 'Africa',
    'Rwanda': 'Africa',
    'Burundi': 'Africa',
    'Liberia': 'Africa',
    'Libya': 'Africa',
    'Central African Republic': 'Africa',
    'Togo': 'Africa',
    'South Sudan': 'Africa',
    'Gabon': 'Africa',
    'Mauritania': 'Africa',
    'Namibia': 'Africa',
    'Botswana': 'Africa',
    'Guinea-Bissau': 'Africa',
    'Gambia': 'Africa',
    'Lesotho': 'Africa',
    'Eritrea': 'Africa',
    'Equatorial Guinea': 'Africa',
    'Cabo Verde': 'Africa',
    'Comoros': 'Africa',
    'Djibouti': 'Africa',
    'Sao Tome and Principe': 'Africa',
    'Seychelles': 'Africa',
    'Mayotte': 'Africa',
    'Western Sahara': 'Africa',
    'Reunion': 'Africa',
    'Congo': 'Africa',
    'Sierra Leone': 'Africa',

    # Oceania
    'Oceania': 'Oceania',
    'Australia and New Zealand': 'Oceania',
    'Melanesia': 'Oceania',
    'Polynesia': 'Oceania',
    'Micronesia': 'Oceania',
    'Australia': 'Oceania',
    'New Zealand': 'Oceania',
    'Fiji': 'Oceania',
    'Papua New Guinea': 'Oceania',
    'Solomon Islands': 'Oceania',
    'Vanuatu': 'Oceania',
    'Samoa': 'Oceania',
    'Tonga': 'Oceania',
    'Kiribati': 'Oceania',
    'Micronesia (Federated States of)': 'Oceania',
    'Marshall Islands': 'Oceania',
    'Palau': 'Oceania',
    'Nauru': 'Oceania',
    'Tuvalu': 'Oceania',
    'Cook Islands': 'Oceania',
    'Niue': 'Oceania',
    'Tokelau': 'Oceania',
    'New Caledonia': 'Oceania',
    'French Polynesia': 'Oceania',
    'Guam': 'Oceania',
    'American Samoa': 'Oceania',
    'Northern Mariana Islands': 'Oceania',
    'Wallis and Futuna': 'Oceania',
    'Norfolk Island': 'Oceania',

    # Special/Other categories
    'World': 'World',
    'Least Developed Countries': 'Special',
    'Low Income Food Deficit Countries': 'Special',
    'Land Locked Developing Countries': 'Special',
    'Small Island Developing States': 'Special',
    'Net Food Importing Developing Countries': 'Special',
}